package com.meFit.meFit.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import javax.persistence.*;

@Entity
@Table(name = "MuscleGroup")
@ApiModel(description = "MuscleGroup Model")
public @Data class MuscleGroup {

    //autogenerated ID which never has to be defined in future functions.
    @ApiModelProperty(notes = "ID of the muscle group", name = "id", value = "1" )
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    //Here the static components of the model
    @ApiModelProperty(notes = "name", name = "name", value = "something"  )
    @Column(name="name",
            nullable = false,
            columnDefinition = "TEXT")
    private String name;

    //related data
    //exercise - muscleGroup - relation
    @ApiModelProperty(notes = "The exercise ID the muscleGroup relates to", name = "exercise ID" )
    @ManyToOne(cascade = {/*CascadeType.ALL, */CascadeType.PERSIST, CascadeType.MERGE, CascadeType.DETACH})
    @JoinColumn(name="exercise_id")
    private Exercise exercise;

    //restricts the output to the exercise ID
    @JsonGetter("exercise")
    public String exercise() {
        if(exercise != null){
            return "/api/v1/exercise/" + exercise.getId();
        }else{
            return null;
        }
    }
}
