package com.meFit.meFit.models;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import javax.persistence.*;

@Entity
@Table(name = "Profile")
@ApiModel(description = "Profile Model")
public @Data class Profile {

    //autogenerated ID which never has to be defined in future functions.
    @ApiModelProperty(notes = "ID of the profile", name = "id", value = "1" )
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    //Here the static components of the model

    @ApiModelProperty(notes = "Weight from the user", name = "weight", value = "70"  )
    @Column(name="weight",
            nullable = false,
            columnDefinition = "TEXT")
    private String weight;

    @ApiModelProperty(notes = "height from the user", name = "height", value = "177" )
    @Column(name="height",
            nullable = false,
            columnDefinition = "TEXT")
    private String height;

    @ApiModelProperty(notes = "Fitness level from the user", name = "fitness level", value = "5" )
    @Column(name="fitnessLevel",
            nullable = false,
            columnDefinition = "TEXT")
    private String fitnessLevel;

    @OneToOne
    @JoinColumn(name = "user_id")
    private User user;

    @OneToOne
    @JoinColumn(name = "goal_id")
    private Goal goal;

}
